name: cs375 
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - numpy=1.26.4
  - matplotlib=3.9.2
  - scikit-learn=1.5.1
  - spacy=3.7.2
  - nltk=3.9.1
  - gensim=4.3.3
  - pytorch=2.3.0
  - pytorch-cpu=2.3.0
  - transformers=4.44.1
  - jupyter=1.0.0
  - jupyter_client<7.0.0
  - nb_conda=2.2.1